apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.k8s.fehe.eu
  annotations:
    cert-manager.io/inject-ca-from: "webhook-coredns-etcd/webhook-certificate"
spec:
  group: v1alpha1.k8s.fehe.eu
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: webhook-coredns-etcd
    namespace: webhook-coredns-etcd
  version: v1alpha1