apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-coredns-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhook-server
    spec:
      serviceAccountName: webhook-coredns-etcd
      containers:
        - name: webhook-server
          image: webhook-server
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: certs
          secret:
            secretName: webhook-certificate