apiVersion: v1
kind: Service
metadata:
  name: webhook-coredns-etcd
  namespace: webhook-coredns-etcd
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: webhook-coredns-etcd
    app.kubernetes.io/component: webhook-server